name: mongodb-cohort

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - mongodb-cohort-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - cohort-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: surajgoraicse
      MONGO_INITDB_ROOT_PASSWORD: surajgoraicse

  mongo-express:
    image: mongo-express
    container_name: mongo-express-cohort
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: surajgoraicse
      ME_CONFIG_MONGODB_ADMINPASSWORD: surajgoraicse
      ME_CONFIG_MONGODB_URL: mongodb://surajgoraicse:surajgoraicse@mongo:27017/?authSource=admin
      ME_CONFIG_BASICAUTH: false

    networks:
      - cohort-network

volumes: 
  mongodb-cohort-volume:

networks:
  cohort-network:
    driver: bridge
